/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WModal {
        "closeModal": (name: string) => Promise<void>;
        "closeOnClick": boolean;
        "name": string;
        "showModal": (name: string) => Promise<void>;
    }
}
declare global {
    interface HTMLWModalElement extends Components.WModal, HTMLStencilElement {
    }
    var HTMLWModalElement: {
        prototype: HTMLWModalElement;
        new (): HTMLWModalElement;
    };
    interface HTMLElementTagNameMap {
        "w-modal": HTMLWModalElement;
    }
}
declare namespace LocalJSX {
    interface WModal {
        "closeOnClick"?: boolean;
        "name"?: string;
        "onBeforeOpen"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "w-modal": WModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "w-modal": LocalJSX.WModal & JSXBase.HTMLAttributes<HTMLWModalElement>;
        }
    }
}
